### ISSUE TITLE
need single select

### ISSUE THREAD

**Issue by kangmifhd** [quartack/bdapter_sample#1]
please add single select item support like radioGroup radioButton

**Comment by quartack** [comment]
> please add single select item support like radioGroup radioButton

sorry for late.
When an item is selected, you can change the selected property of the old selected item to false.
The following link might be helpful.
[layout](https://github.com/quartack/bdapter_sample/blob/main/app/src/main/res/layout/activity_tree.xml#L18), [viewmodel](https://github.com/quartack/bdapter_sample/blob/main/app/src/main/java/com/quartack/bdapter/sample/tree/TreeViewModel.kt#L19)
